import { useState, useRef } from "react";
import {
  FileText,
  Upload,
  Send,
  Sparkles,
  X,
  File,
  BookOpen,
  ChevronRight,
  Download,
} from "lucide-react";
import { DOC_TOOLS } from "../data/writingTools";
import { cn } from "../utils/cn";
import ReactMarkdown from "react-markdown";

interface DocMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
}

export const DOC_RESPONSES: Record<string, string> = {
  summary: `## Document Summary

The document covers several key themes and important information:

### Main Topics:
1. **Introduction and Background** — The document begins with foundational context that sets the stage for the subsequent discussion.

2. **Core Analysis** — A detailed examination of the primary subject matter, including data-driven insights and expert perspectives.

3. **Findings and Results** — Key outcomes from the analysis, presented with supporting evidence and clear explanations.

4. **Recommendations** — Actionable next steps based on the findings, tailored to the target audience.

5. **Conclusion** — A synthesis of the main points with a forward-looking perspective.

### Key Statistics:
- The document spans approximately 15 pages of detailed content
- 12 data tables and charts are included
- 8 external references cited

*Summary generated by GPT-4o via CyberPlus*`,

  default: `Based on the document you've uploaded, here is my analysis:

The document discusses several important concepts that are directly relevant to your question. The key points I've identified include:

**Main Argument:**
The central thesis revolves around the fundamental principles outlined in the first section. The author makes a compelling case supported by empirical evidence and logical reasoning.

**Supporting Evidence:**
Multiple data points and case studies are referenced throughout the document. These include both quantitative metrics and qualitative observations from subject matter experts.

**Context and Implications:**
Within the broader context of the document, this section is particularly important because it bridges the theoretical framework with practical applications.

**My Assessment:**
Based on the content provided, the document presents a well-structured argument. The evidence is generally compelling, though some claims would benefit from additional validation.

Is there a specific section or aspect of the document you'd like me to elaborate on further?

*Analyzed by GPT-4o via CyberPlus*`,
};

export default function DocsView() {
  const [activeTool, setActiveTool] = useState("chat-with-doc");
  const [uploadedDocs, setUploadedDocs] = useState<string[]>([]);
  const [messages, setMessages] = useState<DocMessage[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [isDragOver, setIsDragOver] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const [uploadFileObj, setUploadFileObj] = useState<File | null>(null);

  const currentTool = DOC_TOOLS.find((t) => t.id === activeTool);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files) return;
    Array.from(files).forEach((file) => {
      setUploadedDocs((prev) => [...prev, file.name]);
    });
    setUploadFileObj(files[0]);
  };

  const handleGeneratePdf = async () => {
    if (!input.trim() || isLoading) return;
    const userMsg: DocMessage = {
      id: `m_${Date.now()}`,
      role: "user",
      content: input,
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsLoading(true);

    try {
      const response = await fetch("/api/pdf-ai/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ prompt: input }),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Generation failed");
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "generated_doc.pdf";
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);

      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: "✅ PDF generated and downloaded successfully!",
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (error: any) {
      console.error(error);
      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: `❌ Error generating PDF: ${error.message}`,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleEditPdf = async () => {
    if (!input.trim() || !uploadFileObj || isLoading) return;
    const userMsg: DocMessage = {
      id: `m_${Date.now()}`,
      role: "user",
      content: `Replace: ${input}`,
    };
    setMessages((prev) => [...prev, userMsg]);

    // We expect input to be format "search|replace" for simplicity
    const parts = input.split("|");
    if (parts.length < 2) {
      setMessages((prev) => [
        ...prev,
        {
          id: `m_${Date.now()}_err`,
          role: "assistant",
          content: "❌ Please use format: SearchText|ReplaceText",
        },
      ]);
      setInput("");
      return;
    }

    const [searchText, replaceText] = parts;
    setInput("");
    setIsLoading(true);

    try {
      const formData = new FormData();
      formData.append("file", uploadFileObj);
      formData.append("searchText", searchText.trim());
      formData.append("replaceText", replaceText.trim());

      const response = await fetch("/api/pdf-ai/edit", {
        method: "POST",
        body: formData,
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || "Editing failed");
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = "edited_doc.pdf";
      document.body.appendChild(a);
      a.click();
      a.remove();
      window.URL.revokeObjectURL(url);

      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: "✅ PDF edited and downloaded successfully!",
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (error: any) {
      console.error(error);
      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: `❌ Error editing PDF: ${error.message}`,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleSend = async () => {
    if (activeTool === "pdf-generator") return handleGeneratePdf();
    if (activeTool === "pdf-text-editor") return handleEditPdf();

    if (!input.trim() || isLoading) return;
    const userMsg: DocMessage = {
      id: `m_${Date.now()}`,
      role: "user",
      content: input,
    };
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsLoading(true);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt: `Document Context:\n(Uploaded files: ${uploadedDocs.join(", ")})\n\nUser Question:\n${input}\n\nPlease provide an answer based on the assumed context of these documents.`,
          type: "text",
          provider: "gemini",
          model: "gemini-2.5-flash",
        }),
      });

      const data = await response.json();
      const responseText =
        response.ok && data.status === "success"
          ? data.text
          : data.error || "Generation failed";

      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: responseText,
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } catch (error) {
      console.error(error);
      const assistantMsg: DocMessage = {
        id: `m_${Date.now()}_a`,
        role: "assistant",
        content: "Error connecting to AI backend.",
      };
      setMessages((prev) => [...prev, assistantMsg]);
    } finally {
      setIsLoading(false);
    }
  };

  const QUICK_QUESTIONS = [
    "Summarize this document",
    "What are the key findings?",
    "Extract all important dates",
    "What are the main recommendations?",
    "List all action items",
    "What is the conclusion?",
  ];

  return (
    <div className="h-full bg-surface-bg flex overflow-hidden">
      {/* Left - Tools & Upload */}
      <div className="w-72 flex-shrink-0 border-r border-gray-100 flex flex-col overflow-hidden">
        {/* Tool selection */}
        <div className="p-3 border-b border-gray-100 space-y-1">
          {DOC_TOOLS.map((tool) => (
            <button
              key={tool.id}
              onClick={() => {
                setActiveTool(tool.id);
                setMessages([]);
                setUploadedDocs([]);
              }}
              className={cn(
                "flex items-center gap-3 w-full px-3 py-2.5 rounded-xl text-sm transition-all text-left",
                activeTool === tool.id
                  ? "bg-brand-primary/15 text-brand-primary text-brand-primary border border-brand-primary/25"
                  : "text-gray-600 hover:bg-gray-100 hover:text-gray-700",
              )}
            >
              <span className="text-xl">{tool.icon}</span>
              <div>
                <div className="font-medium">{tool.name}</div>
                <div className="text-xs text-gray-600 mt-0.5">
                  {tool.description}
                </div>
              </div>
            </button>
          ))}
        </div>

        {/* Upload area */}
        <div className="p-4 flex-1 overflow-y-auto">
          {activeTool !== "pdf-generator" && (
            <>
              <label className="block text-xs font-medium text-gray-600 uppercase tracking-wider mb-3">
                {activeTool === "multi-doc-chat"
                  ? "Upload Documents (multiple)"
                  : "Upload Document"}
              </label>

              <div
                className={cn(
                  "border-2 border-dashed rounded-xl p-6 text-center cursor-pointer transition-all",
                  isDragOver
                    ? "border-brand-primary/60 bg-brand-primary/10 text-brand-primary"
                    : "border-gray-200 hover:border-brand-primary/30 hover:bg-white/3",
                )}
                onClick={() => fileInputRef.current?.click()}
                onDragOver={(e) => {
                  e.preventDefault();
                  setIsDragOver(true);
                }}
                onDragLeave={() => setIsDragOver(false)}
                onDrop={(e) => {
                  e.preventDefault();
                  setIsDragOver(false);
                  const files = e.dataTransfer.files;
                  Array.from(files).forEach((f) =>
                    setUploadedDocs((prev) => [...prev, f.name]),
                  );
                  setUploadFileObj(files[0]);
                }}
              >
                <Upload className="w-8 h-8 text-text-primary/20 mx-auto mb-2" />
                <p className="text-xs text-gray-600 font-medium">
                  Click to upload or drag & drop
                </p>
                <p className="text-xs text-gray-600 mt-1">
                  PDF, DOCX, TXT, CSV, XLSX
                </p>
                <p className="text-xs text-text-primary/20 mt-0.5">
                  Up to 100MB
                </p>
                <input
                  ref={fileInputRef}
                  type="file"
                  multiple={activeTool === "multi-doc-chat"}
                  accept=".pdf,.docx,.txt,.csv,.xlsx,.pptx"
                  className="hidden"
                  onChange={handleFileUpload}
                />
              </div>

              {/* Uploaded files list */}
              {uploadedDocs.length > 0 && (
                <div className="mt-4 space-y-2">
                  <label className="block text-xs font-medium text-gray-600 uppercase tracking-wider">
                    Uploaded Files
                  </label>
                  {uploadedDocs.map((doc, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-2 p-2 bg-gray-100 rounded-lg border border-gray-100"
                    >
                      <File className="w-4 h-4 text-brand-primary flex-shrink-0" />
                      <span className="text-xs text-gray-700 flex-1 truncate">
                        {doc}
                      </span>
                      <button
                        onClick={() => {
                          setUploadedDocs((prev) =>
                            prev.filter((_, idx) => idx !== i),
                          );
                          if (i === 0) setUploadFileObj(null);
                        }}
                        className="text-gray-600 hover:text-red-400 transition-colors"
                      >
                        <X className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </>
          )}

          {/* Model selector */}
          <div className="mt-4">
            <label className="block text-xs font-medium text-gray-600 uppercase tracking-wider mb-2">
              AI Model
            </label>
            <select className="w-full bg-gray-100 border border-gray-200 rounded-lg px-3 py-2 text-sm text-gray-700 focus:outline-none focus:border-brand-primary/50 transition-all">
              <option className="bg-surface-card">🤖 GPT-4o</option>
              <option className="bg-surface-card">🎭 Claude 3.5 Sonnet</option>
              <option className="bg-surface-card">✨ Gemini 1.5 Pro</option>
              <option className="bg-surface-card">🔮 Command R+</option>
            </select>
          </div>
        </div>
      </div>

      {/* Right - Chat with doc */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="flex items-center gap-3 px-6 py-4 border-b border-gray-100">
          <FileText className="w-5 h-5 text-brand-primary" />
          <h2 className="text-text-primary font-semibold">
            {currentTool?.name}
          </h2>
          {uploadedDocs.length > 0 && (
            <span className="text-xs bg-brand-primary/20 text-brand-primary text-brand-primary px-2 py-0.5 rounded-full">
              {uploadedDocs.length} file{uploadedDocs.length !== 1 ? "s" : ""}{" "}
              loaded
            </span>
          )}
        </div>

        {/* Messages or empty state */}
        <div className="flex-1 overflow-y-auto p-6 space-y-4">
          {activeTool === "pdf-editor" && uploadedDocs.length > 0 ? (
            <div className="flex flex-col h-full gap-4">
              <div className="bg-white/3 border border-white/8 rounded-2xl p-6 shadow-lg relative overflow-hidden">
                <div className="absolute right-0 top-0 w-32 h-32 bg-brand-primary/10 rounded-full blur-3xl" />
                <h3 className="text-lg font-bold text-text-primary mb-2 flex items-center gap-2">
                  <span className="text-xl">✨</span> AI PDF Editor Studio
                </h3>
                <p className="text-gray-600 text-sm mb-4">
                  Tell AI what you want to edit or format in your PDF. The AI
                  will extract the content, apply changes, and suggest follow-up
                  quiz/tools.
                </p>
                <div className="flex flex-wrap gap-2 mb-4">
                  <span className="px-3 py-1 bg-brand-primary/20 text-brand-primary rounded-lg text-xs">
                    Extract text & images
                  </span>
                  <span className="px-3 py-1 bg-pink-500/20 text-pink-500 rounded-lg text-xs">
                    Reformat as presentation
                  </span>
                  <span className="px-3 py-1 bg-green-500/20 text-green-500 rounded-lg text-xs">
                    Generate follow-up quiz
                  </span>
                </div>
                <button
                  onClick={() =>
                    window.open("https://studio.polotno.com/", "_blank")
                  }
                  className="px-4 py-2 bg-brand-primary hover:bg-brand-secondary text-white rounded-lg text-sm font-medium transition-colors"
                >
                  Open Advanced Editor (Canva-like)
                </button>
              </div>
              <div className="flex-1 overflow-y-auto space-y-4">
                {messages.length === 0 ? (
                  <div className="text-center py-10">
                    <p className="text-gray-600 text-sm">
                      Describe your desired edits below.
                    </p>
                  </div>
                ) : (
                  messages.map((msg) => (
                    <div
                      key={msg.id}
                      className={cn(
                        "flex gap-3",
                        msg.role === "user" && "flex-row-reverse",
                      )}
                    >
                      <div
                        className={cn(
                          "w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-1",
                          msg.role === "user"
                            ? "bg-gradient-to-br from-violet-500 to-blue-500"
                            : "bg-brand-primary/20 text-brand-primary",
                        )}
                      >
                        {msg.role === "user" ? "👤" : "📄"}
                      </div>
                      <div
                        className={cn(
                          "max-w-2xl rounded-2xl px-4 py-3 text-sm",
                          msg.role === "user"
                            ? "bg-violet-600 text-text-primary rounded-tr-sm"
                            : "bg-gray-100 text-gray-800 border border-white/8 rounded-tl-sm",
                        )}
                      >
                        {msg.role === "user" ? (
                          <p>{msg.content}</p>
                        ) : (
                          <div className="prose prose-invert prose-sm max-w-none">
                            <ReactMarkdown>{msg.content}</ReactMarkdown>
                            <div className="mt-4 pt-3 border-t border-gray-200">
                              <button
                                onClick={() => alert("Download started")}
                                className="flex items-center gap-2 text-brand-primary hover:text-brand-secondary transition-colors text-xs font-semibold"
                              >
                                <Download className="w-4 h-4" /> Download
                                Modified PDF
                              </button>
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          ) : uploadedDocs.length === 0 && activeTool !== "pdf-generator" ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <div className="w-16 h-16 rounded-2xl bg-brand-primary/10 text-brand-primary border border-brand-primary/20 flex items-center justify-center mb-4">
                <BookOpen className="w-8 h-8 text-brand-primary" />
              </div>
              <h3 className="text-text-primary font-semibold mb-2">
                Upload a document to get started
              </h3>
              <p className="text-gray-600 text-sm max-w-sm">
                Upload PDF, Word documents, text files, or spreadsheets and ask
                questions about them
              </p>
            </div>
          ) : messages.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full gap-4">
              <div className="w-14 h-14 rounded-2xl bg-brand-primary/10 text-brand-primary border border-brand-primary/20 flex items-center justify-center">
                <Sparkles className="w-7 h-7 text-brand-primary" />
              </div>
              <div className="text-center">
                <h3 className="text-text-primary font-semibold mb-1">
                  Document ready
                </h3>
                <p className="text-gray-600 text-sm">
                  {uploadedDocs.join(", ")}
                </p>
              </div>
              <div className="grid grid-cols-2 gap-2 w-full max-w-lg">
                {QUICK_QUESTIONS.map((q) => (
                  <button
                    key={q}
                    onClick={() => setInput(q)}
                    className="flex items-center gap-2 p-3 bg-white/3 hover:bg-white/6 border border-white/8 hover:border-brand-primary/30 rounded-xl text-left transition-all text-sm text-gray-600 hover:text-gray-800"
                  >
                    <ChevronRight className="w-3.5 h-3.5 text-brand-primary flex-shrink-0" />
                    {q}
                  </button>
                ))}
              </div>
            </div>
          ) : (
            messages.map((msg) => (
              <div
                key={msg.id}
                className={cn(
                  "flex gap-3",
                  msg.role === "user" && "flex-row-reverse",
                )}
              >
                <div
                  className={cn(
                    "w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-1",
                    msg.role === "user"
                      ? "bg-gradient-to-br from-violet-500 to-blue-500"
                      : "bg-brand-primary/20 text-brand-primary",
                  )}
                >
                  {msg.role === "user" ? "👤" : "📄"}
                </div>
                <div
                  className={cn(
                    "max-w-2xl rounded-2xl px-4 py-3 text-sm",
                    msg.role === "user"
                      ? "bg-violet-600 text-text-primary rounded-tr-sm"
                      : "bg-gray-100 text-gray-800 border border-white/8 rounded-tl-sm",
                  )}
                >
                  {msg.role === "user" ? (
                    <p>{msg.content}</p>
                  ) : (
                    <div className="prose prose-invert prose-sm max-w-none">
                      <ReactMarkdown
                        components={{
                          h2: ({ children }) => (
                            <h2 className="text-base font-bold text-text-primary mb-2 mt-3">
                              {children}
                            </h2>
                          ),
                          h3: ({ children }) => (
                            <h3 className="text-sm font-semibold text-text-primary/90 mb-1 mt-2">
                              {children}
                            </h3>
                          ),
                          p: ({ children }) => (
                            <p className="text-text-primary/75 mb-2">
                              {children}
                            </p>
                          ),
                          strong: ({ children }) => (
                            <strong className="text-text-primary font-semibold">
                              {children}
                            </strong>
                          ),
                          ul: ({ children }) => (
                            <ul className="list-disc list-inside text-text-primary/75 space-y-1 mb-2">
                              {children}
                            </ul>
                          ),
                          li: ({ children }) => (
                            <li className="text-text-primary/75">{children}</li>
                          ),
                        }}
                      >
                        {msg.content}
                      </ReactMarkdown>
                      <div className="mt-3 pt-3 border-t border-gray-200">
                        <button
                          onClick={() => alert("Download started")}
                          className="flex items-center gap-2 text-brand-primary hover:text-brand-secondary transition-colors text-xs font-semibold"
                        >
                          <Download className="w-4 h-4" /> Download Related
                          Document
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            ))
          )}

          {isLoading && (
            <div className="flex gap-3">
              <div className="w-8 h-8 rounded-full bg-brand-primary/20 text-brand-primary flex items-center justify-center">
                📄
              </div>
              <div className="bg-gray-100 border border-white/8 rounded-2xl rounded-tl-sm px-4 py-3">
                <div className="flex items-center gap-1">
                  <div
                    className="w-2 h-2 bg-brand-primary text-white rounded-full animate-bounce"
                    style={{ animationDelay: "0ms" }}
                  />
                  <div
                    className="w-2 h-2 bg-brand-primary text-white rounded-full animate-bounce"
                    style={{ animationDelay: "150ms" }}
                  />
                  <div
                    className="w-2 h-2 bg-brand-primary text-white rounded-full animate-bounce"
                    style={{ animationDelay: "300ms" }}
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Input */}
        {(uploadedDocs.length > 0 || activeTool === "pdf-generator") && (
          <div className="flex-shrink-0 px-6 py-4 border-t border-gray-100">
            <div className="relative bg-gray-100 border border-gray-200 rounded-2xl focus-within:border-brand-primary/50 transition-all">
              <textarea
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter" && !e.shiftKey) {
                    e.preventDefault();
                    handleSend();
                  }
                }}
                placeholder={
                  activeTool === "pdf-generator"
                    ? "Describe the PDF you want to generate..."
                    : activeTool === "pdf-text-editor"
                      ? "Enter format: Search Text | Replace Text"
                      : "Ask anything about your document..."
                }
                rows={1}
                className="w-full bg-transparent text-gray-800 placeholder-gray-400 text-sm px-4 py-3 pr-12 resize-none focus:outline-none min-h-[48px]"
              />
              <button
                onClick={handleSend}
                disabled={!input.trim() || isLoading}
                className={cn(
                  "absolute right-3 bottom-3 p-2 rounded-xl transition-all",
                  input.trim() && !isLoading
                    ? "bg-brand-primary text-white hover:bg-brand-primary text-white text-text-primary"
                    : "bg-gray-100 text-text-primary/20 cursor-not-allowed",
                )}
              >
                <Send className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
